<a href="https://colab.research.google.com/github/Saroj-thapa/Introduction-To-AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2] = 10

In [8]:
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,11) # creates arryas with evenly spcaed numbers within a spec

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

 # Multidmensional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [24]:
n[0,1] = 20

In [25]:
n[2] = [1,1,1]

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [27]:
n[:,2] = [0,1,2]

In [28]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly generated arrays
Numpy can create arrays

In [34]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [36]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

Element-wise You can perform operation on entire arrays

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [41]:
b = (10+(a*2))
b

array([10, 12, 14, 16, 18])

In [42]:
a >=2

array([False, False,  True,  True,  True])

In [43]:
a>b

array([False, False, False, False, False])

Summarizing
NUmpy provides function for

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
a.std()

1.4142135623730951

In [46]:
a.min()

0

In [47]:
a.max()

4

In [48]:
a.sum()

10